export function generateMetadata() {
    return {
        title: "Blog",
        openGraph: {
            title: "Blog",
            description: "Generated by Ynov team",
            type: "website",
            url: "https://ynov-website.vercel.app/Blog",
            siteName: "Ynov",
            images: [
                {
                    url: "https://ynov-website.vercel.app/og.png",
                    width: 800,
                    height: 600,
                },
            ],
        },
        twitter: {
            card: "summary_large_image",
            title: "Blog",
            description: "Generated by Ynov team",
            images: ["https://ynov-website.vercel.app/og.png"],
        },
        robots: {
            index: true,
            follow: true,
            nocache: true,
        },
    };
}
