import SkeletonLoader from "../../../components/SkeletonLoader";
import React, { useState ,useEffect} from "react";


export function generateMetadata() {
    return {
        title: "Blog",
        openGraph: {
            title: "Blog",
            description: "Generated by Ynov team",
            type: "website",
            url: "https://ynov-website.vercel.app/Blog",
            siteName: "Ynov",
            images: [
                {
                    url: "https://ynov-website.vercel.app/og.png",
                    width: 800,
                    height: 600,
                },
            ],
        },
        twitter: {
            card: "summary_large_image",
            title: "Blog",
            description: "Generated by Ynov team",
            images: ["https://ynov-website.vercel.app/og.png"],
        },
        robots: {
            index: true,
            follow: true,
            nocache: true,
        },
    };
}

export default function Blog() {
      const [isLoading, setIsLoading] = useState(true);

        useEffect(() => {
          const timer = setTimeout(() => setIsLoading(false), 2000);
          return () => clearTimeout(timer);
        }, []);

    return (
        <> 
         {isLoading ? (
        <SkeletonLoader />
      ) : (
        
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <h1 className="text-3xl font-bold underline">Blog page</h1>
        </main>
        
      )} 
       </>
    );
}
