import "./globals.css";
import Head from "next/head";

const helveticaNeue = {
  variable: "--font-helvetica",
  style: {
    fontFamily: "Helvetica Neue, Arial, sans-serif"
  }
};

export const metadata = {
  title: {
    default: "Bab Rayan",
    template: "%s | Bab Rayan",
  },
  description: "Generated by Ynov team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="https://firebasestorage.googleapis.com/v0/b/bab-rayan-b04a0.firebasestorage.app/o/mini_logo.png?alt=media&token=f0e45650-ec81-4aea-838a-95a0dfad67cf" />
      </Head>
      <body className={`${helveticaNeue.variable} antialiased`} style={helveticaNeue.style}>
        {children}
      </body>
    </html>
  );
}
