"use client";

import { usePathname  } from "next/navigation";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import { FaHandHoldingHeart } from "react-icons/fa";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"], 
  variable: "--font-roboto",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  weight: ["400", "700"],
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: {
//     default: "Bab Rayan",
//     template: "%s | Bab Rayan",
//   },
//   description: "Generated by Ynov team",
// };



export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Check if the URL includes '/dashboard'
  const isDashboard = pathname?.includes("/dashboard");

  return (
    <html lang="en">
      <body className={`${roboto.variable} ${robotoMono.variable} antialiased`} >
        { !isDashboard && <NavBar />}
        <section>
          {children}
        </section>
        { !isDashboard && <Footer />}


        {!isDashboard ?
        <button onClick={() => window.location.href = "donation"} className='red_color don_icon_animate' title='Faire un DON'>
          <FaHandHoldingHeart />

        </button> : null}
      </body>
    </html>
  );
}
